import { DailyChallenge } from '../types';

export const CHALLENGE_CONTENT: Omit<DailyChallenge, 'completed' | 'unlockedAt' | 'completedAt'>[] = [
  {
    day: 1,
    title: 'Welcome to Your Journey',
    category: 'mindset',
    description: 'Today marks the beginning of your transformation. Set the foundation for success.',
    mission: 'Create your ideal morning routine and execute it tomorrow. Write down 3 specific goals for this 30-day journey.',
    tips: [
      'Wake up at the same time each day',
      'Start with 5 minutes of movement',
      'No phone for the first 30 minutes',
      'Write your goals somewhere visible',
    ],
    xpReward: 20,
  },
  {
    day: 2,
    title: 'Master Your Morning',
    category: 'habits',
    description: 'How you start your day determines how you live your day.',
    mission: 'Execute your morning routine without checking your phone for 1 hour after waking up.',
    tips: [
      'Put your phone in another room overnight',
      'Use a real alarm clock',
      'Have your routine written down',
      'Celebrate small wins',
    ],
    xpReward: 15,
  },
  {
    day: 3,
    title: 'Hydration Foundation',
    category: 'health',
    description: 'Your body is 60% water. Proper hydration changes everything.',
    mission: 'Drink 2 liters of water today. Track every glass and drink 500ml immediately upon waking.',
    tips: [
      'Drink a full glass before coffee',
      'Keep a water bottle visible at all times',
      'Set hourly reminders',
      'Notice your energy levels increase',
    ],
    xpReward: 15,
  },
  {
    day: 4,
    title: 'Digital Minimalism',
    category: 'productivity',
    description: 'Take back control of your attention from the algorithm.',
    mission: 'Delete or log out of 3 social media apps. Keep them off for 24 hours minimum.',
    tips: [
      'Start with the most addictive one',
      'Notice urges without acting on them',
      'Replace scrolling with reading',
      'Track how much time you save',
    ],
    xpReward: 20,
  },
  {
    day: 5,
    title: 'Movement is Medicine',
    category: 'health',
    description: 'Your body is designed to move. Movement creates energy.',
    mission: 'Complete 30 minutes of intentional exercise. It can be walking, running, gym, or yoga.',
    tips: [
      'Start with a 5-min warm-up',
      'Pick something you enjoy',
      'Morning movement = energy all day',
      'Focus on consistency over intensity',
    ],
    xpReward: 15,
  },
  {
    day: 6,
    title: 'Deep Work Session',
    category: 'productivity',
    description: 'Shallow work is easy. Deep work is rare and valuable.',
    mission: 'Complete 90 minutes of focused, uninterrupted work on your most important project. No phone, no distractions.',
    tips: [
      'Turn off all notifications',
      'Use a timer (Pomodoro: 25 min work, 5 min break)',
      'Have a specific outcome in mind',
      'Work in a clean, dedicated space',
    ],
    xpReward: 20,
  },
  {
    day: 7,
    title: 'Weekly Reflection',
    category: 'mindset',
    description: 'You\'ve completed week 1. Reflection creates growth.',
    mission: 'Write a 10-minute reflection: What worked? What didn\'t? What will you change next week?',
    tips: [
      'Be honest with yourself',
      'Celebrate every win, even small ones',
      'Identify your biggest obstacle',
      'Adjust your systems, not just effort',
    ],
    xpReward: 25,
  },
  {
    day: 8,
    title: 'Nutrition Reset',
    category: 'health',
    description: 'You can\'t out-exercise a bad diet. Food is fuel.',
    mission: 'Eat 3 whole-food meals today. No processed snacks, no sugar. Cook at least one meal yourself.',
    tips: [
      'Plan your meals the night before',
      'Protein + vegetables in every meal',
      'Drink water before you eat',
      'Notice how clean food = clean energy',
    ],
    xpReward: 15,
  },
  {
    day: 9,
    title: 'Learning Sprint',
    category: 'productivity',
    description: 'Read for 30 minutes or learn a new skill.',
    mission: 'Spend 30 minutes learning something valuable. Read a book, watch an educational video, or practice a skill.',
    tips: [
      'Choose something aligned with your goals',
      'Take notes while learning',
      'Apply what you learn immediately',
      'Consistency beats intensity',
    ],
    xpReward: 15,
  },
  {
    day: 10,
    title: 'Social Connection',
    category: 'social',
    description: 'Humans are wired for connection. Quality > quantity.',
    mission: 'Have a real conversation with someone you care about. Phone call or in-person (no texting).',
    tips: [
      'Put your phone away during conversation',
      'Ask deep questions',
      'Listen more than you talk',
      'Express genuine appreciation',
    ],
    xpReward: 15,
  },
  {
    day: 11,
    title: 'Sleep Optimization',
    category: 'health',
    description: 'Sleep is the foundation. Everything breaks without it.',
    mission: 'Get 8 hours of sleep. No screens 1 hour before bed. Create a wind-down routine.',
    tips: [
      'Set a bedtime alarm',
      'Make your room dark and cool',
      'Read or journal before bed',
      'No caffeine after 2 PM',
    ],
    xpReward: 20,
  },
  {
    day: 12,
    title: 'Gratitude Practice',
    category: 'mindset',
    description: 'What you focus on expands. Choose gratitude.',
    mission: 'Write down 10 things you\'re grateful for. Then tell someone why you appreciate them.',
    tips: [
      'Be specific, not generic',
      'Include small things (coffee, sunshine)',
      'Feel the emotion as you write',
      'Make this a daily habit',
    ],
    xpReward: 15,
  },
  {
    day: 13,
    title: 'Environment Design',
    category: 'productivity',
    description: 'Your environment shapes your behavior. Design it intentionally.',
    mission: 'Clean and organize your primary workspace. Remove all distractions. Add something inspiring.',
    tips: [
      'Clear desk = clear mind',
      'Remove visible snacks/phone',
      'Add plants or motivational quotes',
      'Make good behaviors obvious',
    ],
    xpReward: 15,
  },
  {
    day: 14,
    title: 'Halfway Point Reflection',
    category: 'mindset',
    description: 'You\'re halfway through. This is where most people quit. You won\'t.',
    mission: 'Review your progress. Update your goals. Recommit to the next 16 days with renewed energy.',
    tips: [
      'Look at how far you\'ve come',
      'Identify your biggest breakthrough',
      'What needs to change in week 3?',
      'The second half is where transformation happens',
    ],
    xpReward: 30,
  },
  {
    day: 15,
    title: 'Cold Exposure',
    category: 'health',
    description: 'Discomfort is growth. Start with cold showers.',
    mission: 'Take a cold shower for 2 minutes. Focus on your breath and embrace the discomfort.',
    tips: [
      'Start warm, end with 2 min cold',
      'Breathe slowly and deeply',
      'This trains mental resilience',
      'Notice the energy boost after',
    ],
    xpReward: 20,
  },
  {
    day: 16,
    title: 'Financial Clarity',
    category: 'productivity',
    description: 'Money stress destroys focus. Get clear on your finances.',
    mission: 'Track every dollar you spend today. Review your subscriptions and cancel 1 you don\'t use.',
    tips: [
      'Use a simple expense tracker',
      'Awareness precedes change',
      'Small leaks sink big ships',
      'Automate your savings',
    ],
    xpReward: 15,
  },
  {
    day: 17,
    title: 'Skill Stack',
    category: 'productivity',
    description: 'Practice a valuable skill for 1 hour.',
    mission: 'Dedicate 1 focused hour to practicing a skill that will 10x your value (coding, writing, speaking, etc.).',
    tips: [
      'Deliberate practice > casual practice',
      'Focus on your weak points',
      'Get feedback or track progress',
      'Consistency compounds',
    ],
    xpReward: 20,
  },
  {
    day: 18,
    title: 'Fasting Experiment',
    category: 'health',
    description: 'Try intermittent fasting: 16 hours fasting, 8 hour eating window.',
    mission: 'Fast for 16 hours (e.g., last meal at 8 PM, first meal at 12 PM next day). Track your energy and focus.',
    tips: [
      'Drink water and black coffee/tea',
      'Notice mental clarity around hour 12-16',
      'Break fast with protein and vegetables',
      'This is a tool, not a religion',
    ],
    xpReward: 20,
  },
  {
    day: 19,
    title: 'Creative Expression',
    category: 'mindset',
    description: 'Creativity is intelligence having fun.',
    mission: 'Create something today. Write, draw, build, film, design—anything. Just make something from nothing.',
    tips: [
      'Don\'t judge, just create',
      'Set a 30-minute timer',
      'Share it with someone',
      'Creativity is a muscle',
    ],
    xpReward: 15,
  },
  {
    day: 20,
    title: 'No Complaints Challenge',
    category: 'mindset',
    description: 'Complaining rewires your brain for negativity.',
    mission: 'Go 24 hours without complaining—out loud or in your head. Replace complaints with solutions or gratitude.',
    tips: [
      'Catch yourself when you complain',
      'Ask: "What can I control here?"',
      'Reframe problems as challenges',
      'This changes your entire mindset',
    ],
    xpReward: 20,
  },
  {
    day: 21,
    title: 'Habit Audit',
    category: 'habits',
    description: 'You are your habits. Time to optimize.',
    mission: 'List all your daily habits. Identify 1 bad habit to eliminate and 1 good habit to add.',
    tips: [
      'Be brutally honest',
      'Replace bad habits, don\'t just remove them',
      'Stack new habits onto existing ones',
      'Track your new habit daily',
    ],
    xpReward: 20,
  },
  {
    day: 22,
    title: 'Relationship Investment',
    category: 'social',
    description: 'Your network is your net worth.',
    mission: 'Reach out to 3 people you admire or want to reconnect with. Genuine message, no ask.',
    tips: [
      'Be specific about what you appreciate',
      'Offer value before asking',
      'Quality relationships > quantity',
      'Play the long game',
    ],
    xpReward: 15,
  },
  {
    day: 23,
    title: 'Content Creation',
    category: 'productivity',
    description: 'Stop consuming, start creating.',
    mission: 'Create and publish one piece of content: tweet, video, blog post, or photo. Share your journey.',
    tips: [
      'Document, don\'t create',
      'Teach what you\'re learning',
      'Imperfect action beats perfect inaction',
      'Building in public builds accountability',
    ],
    xpReward: 20,
  },
  {
    day: 24,
    title: 'Mindfulness Practice',
    category: 'mindset',
    description: 'Be here now. Most suffering lives in past or future.',
    mission: 'Meditate for 15 minutes. Use an app (Headspace, Calm) or just focus on your breath.',
    tips: [
      'Sit comfortably, back straight',
      'Focus on breath, return when mind wanders',
      'There is no "bad" meditation',
      'The practice IS the point',
    ],
    xpReward: 15,
  },
  {
    day: 25,
    title: 'Energy Audit',
    category: 'health',
    description: 'Manage energy, not time.',
    mission: 'Track your energy levels every 2 hours today. Identify your peak performance windows.',
    tips: [
      'Rate energy 1-10 at 8am, 10am, 12pm, 2pm, 4pm, 6pm, 8pm',
      'Notice patterns',
      'Schedule hard tasks during peaks',
      'Protect your energy ruthlessly',
    ],
    xpReward: 15,
  },
  {
    day: 26,
    title: 'Give Back',
    category: 'social',
    description: 'Success without contribution is meaningless.',
    mission: 'Help someone today. Mentor, volunteer, donate, or simply solve someone\'s problem.',
    tips: [
      'Give without expecting return',
      'Use your unique skills',
      'Even 30 minutes makes a difference',
      'Fulfillment comes from service',
    ],
    xpReward: 20,
  },
  {
    day: 27,
    title: 'Vision Board',
    category: 'mindset',
    description: 'Clarity creates momentum.',
    mission: 'Create a vision for the next 90 days. Write down exactly what you want to accomplish and why.',
    tips: [
      'Be specific and measurable',
      'Include all life areas (health, wealth, relationships)',
      'Write in present tense ("I am...")',
      'Review this daily',
    ],
    xpReward: 20,
  },
  {
    day: 28,
    title: 'Peak Performance Day',
    category: 'productivity',
    description: 'Execute your perfect day from start to finish.',
    mission: 'Execute your ideal routine perfectly: morning routine, deep work, exercise, nutrition, learning, reflection.',
    tips: [
      'Plan every hour the night before',
      'Eliminate all distractions',
      'Say no to everything else',
      'This is your new baseline',
    ],
    xpReward: 25,
  },
  {
    day: 29,
    title: 'Lessons Learned',
    category: 'mindset',
    description: 'Extract wisdom from the journey.',
    mission: 'Write down the 10 biggest lessons from this 30-day challenge. What changed? Who did you become?',
    tips: [
      'Review your daily reflections',
      'What surprised you most?',
      'What will you continue?',
      'What identity shifts occurred?',
    ],
    xpReward: 25,
  },
  {
    day: 30,
    title: 'The Beginning',
    category: 'mindset',
    description: 'This isn\'t the end. It\'s day 1 of the rest of your life.',
    mission: 'Celebrate how far you\'ve come. Then plan your next 30 days. Transformation is a lifestyle, not a sprint.',
    tips: [
      'Acknowledge every win',
      'Share your results with someone',
      'What systems will you maintain?',
      'The real challenge: sustain this forever',
    ],
    xpReward: 50,
  },
];
