import { JournalTemplate, RoutineTemplate } from "../types";

export const defaultTemplate: RoutineTemplate = {
  id: 'default-1',
  name: 'Energizing Morning',
  description: 'Start your day with energy and intention',
  isActive: true,
  createdAt: new Date(),
  totalDuration: 30,
  steps: [
    {
      id: 'step-1',
      title: 'Hydrate',
      description: 'Drink a full glass of water',
      duration: 2,
      icon: '💧',
      order: 1,
      isOptional: false,
      completedToday: false,
    },
    {
      id: 'step-2',
      title: 'Stretch',
      description: '5-minute gentle stretching',
      duration: 5,
      icon: '🧘',
      order: 2,
      isOptional: false,
      completedToday: false,
    },
    {
      id: 'step-3',
      title: 'Mindfulness',
      description: 'Breathe and set intentions',
      duration: 5,
      icon: '🧠',
      order: 3,
      isOptional: false,
      completedToday: false,
    },
    {
      id: 'step-4',
      title: 'Plan Your Day',
      description: 'Review your schedule and priorities',
      duration: 8,
      icon: '📋',
      order: 4,
      isOptional: false,
      completedToday: false,
    },
    {
      id: 'step-5',
      title: 'Journal',
      description: 'Answer your morning questions',
      duration: 10,
      icon: '📝',
      order: 5,
      isOptional: true,
      completedToday: false,
    },
  ],
};

export const defaultTemplateJournal: JournalTemplate = {
  id: 'default-journal-1',
  name: 'Morning Reflection',
  isActive: true,
  createdAt: new Date(),
  questions: [
    {
      id: 'q1',
      question: 'What are 3 things youre grateful for today?',
      type: 'text',
      placeholder: '1.\n2.\n3.',
      order: 1,
      isActive: true,
      category: 'gratitude',
    },
    {
      id: 'q2',
      question: 'What is your main goal for today?',
      type: 'text',
      placeholder: 'My focus today is...',
      order: 2,
      isActive: true,
      category: 'goals',
    },
    {
      id: 'q3',
      question: 'How are you feeling right now?',
      type: 'scale',
      scaleMin: 1,
      scaleMax: 10,
      order: 3,
      isActive: true,
      category: 'mood',
    },
    {
      id: 'q4',
      question: 'What would make today great?',
      type: 'text',
      placeholder: 'Today would be great if...',
      order: 4,
      isActive: true,
      category: 'reflection',
    },
  ],
};